org.gradle.daemon=false
org.gradle.jvmargs=-Xmx5120m -Dfile.encoding=UTF-8
org.gradle.workers.max=5
org.gradle.parallel=true

systemProp.file.encoding=UTF-8
kotlin.incremental=false
kotlin.compiler.execution.strategy=in-process
